# Generated by Django 5.0.3 on 2024-06-30 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for order', primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('enroute', 'Enroute'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('vendor_id', models.CharField(max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
