# Generated by Django 5.0.3 on 2024-06-27 16:04

import django.db.models.deletion
import product.models
import shortuuid.django_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=8, max_length=8, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='product.jpg', null=True, upload_to=product.models.user_directory_path)),
                ('description', models.TextField(default='', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('2.99'), max_digits=12, null=True)),
                ('product_status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out Of Stock'), ('in_production', 'In Production')], default='available', max_length=15)),
                ('stock_count', models.IntegerField(blank=True, default='10', max_length=100, null=True)),
                ('quantity', models.FloatField(default=1.0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
