# Generated by Django 5.0.3 on 2024-06-23 10:22

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=8, max_length=15, null=True, prefix='')),
                ('name', models.CharField(default='groceries', max_length=100)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=12)),
                ('product_status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out Of Stock'), ('in_production', 'In Production')], default='available', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
