# Generated by Django 5.0.3 on 2024-06-24 11:24

import product.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=product.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=8, max_length=8, prefix=''),
        ),
    ]
