# Generated by Django 5.0.3 on 2024-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=10, help_text='how many of the product do you have in store?'),
        ),
    ]
