# Generated by Django 5.0.3 on 2024-06-29 10:09

import product.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='Write the description for the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', help_text='Upload the picture of the product', null=True, upload_to=product.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='Input the name of the price', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.99'), help_text='input the old price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='input the current price for the product', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out Of Stock'), ('in_production', 'In Production')], default='available', help_text='select the availability of the product', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='Input the number of quantity you have in store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, default='10', help_text='how many of the product do you have in store?', null=True),
        ),
    ]
