# Generated by Django 5.0.3 on 2024-06-29 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_id_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for product', primary_key=True, serialize=False),
        ),
    ]
