# Generated by Django 5.0.3 on 2024-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='images'),
        ),
    ]
